### ISSUE TITLE
Reboot task fails

### ISSUE THREAD

**Issue by SirRawlins** [motdotla/ansible-pi#2]
Pushed the config changes and updated the apt packages just fine, but failed to reboot at the end.

```
fatal: [192.168.1.80]: FAILED! => {"changed": true, "cmd": ["/sbin/reboot", "-t", "now"], "delta": "0:00:00.045698", "end": "2016-02-18 11:20:00.375066", "failed": true, "rc": 1, "start": "2016-02-18 11:20:00.329368", "stderr": "/sbin/reboot: invalid option -- 't'", "stdout": "", "stdout_lines": [], "warnings": []}
```

You don't need the -t option for reboot, I believe that `/sbin/reboot` would suffice in the Playbook?

**Comment by motdotla** [comment]
@SirRawlins Was this isolated or did you see it repeatedly?

**Comment by SirRawlins** [comment]
I can't honestly remember @motdotla - sorry.

**Comment by chrowe** [comment]
I am having a similar issue with Ansible 2.2.0.0 on MacOS 10.12.3

It seems to be an issue with `command` not liking `&&`
If I do  `command: reboot` it works.
and
If I do `shell: sleep 2 && reboot` it works.
