### ISSUE TITLE
ansible_ssh_host variable not working in local_action: wait_for

### ISSUE THREAD

**Issue by chrowe** [motdotla/ansible-pi#5]
There is an issue open for this with Ansible https://github.com/ansible/ansible/issues/21269

A workaround is suggested here https://github.com/ansible/ansible/issues/14237#issuecomment-277340327 which worked for me

```
- set_fact:
    real_ansible_host: "{{ ansible_host }}"
```
...
```
- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
```

**Comment by prabhakarsultane** [comment]
Thanks for the solution
